'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmEGram1

    '''<summary>
    '''localize1Resource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize1Resource1 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localizeResource2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localizeResource2 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''lnkService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkService As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbltotalservices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltotalservices As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkgram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkgram As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbltotalgram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltotalgram As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''localize1Resource3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize1Resource3 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''dlServiceList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlServiceList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''localize1Resource30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize1Resource30 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''dlTopGramPanchayat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlTopGramPanchayat As Global.System.Web.UI.WebControls.DataList
End Class
