'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Sitemap

    '''<summary>
    '''lblsitemap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsitemap As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Service control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Service As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''citizenservice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents citizenservice As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Digitallocker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Digitallocker As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Localize1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Localize1 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''gARVIRegistered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gARVIRegistered As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''ElectionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ElectionID As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''AadharCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AadharCard As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''PANCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PANCard As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''VehicleRegistration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VehicleRegistration As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''AnyRoR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnyRoR As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Employm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Employm As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''GovernmentJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GovernmentJobs As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Industry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Industry As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Revenue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Revenue As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Incomecertificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Incomecertificate As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''CreamylayerCertificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreamylayerCertificate As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''MinorityCertificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MinorityCertificate As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''EducationallyBackward control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EducationallyBackward As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''CentralGoverment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CentralGoverment As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''SeniorCitizen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeniorCitizen As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''ReligiousMinority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReligiousMinority As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''STCaste control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents STCaste As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''TemporaryResidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TemporaryResidence As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Moreid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Moreid As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Panchayatid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panchayatid As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''EconomicallyBackward control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EconomicallyBackward As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Widow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Widow As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Income control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Income As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Nonid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nonid As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''CentralGovermentid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CentralGovermentid As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''TempResidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TempResidence As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''More control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents More As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''StudentCorner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StudentCorner As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Hostel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hostel As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Scholarship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Scholarship As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''StudentTablet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StudentTablet As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Tourism control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tourism As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''GujaratTourism control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GujaratTourism As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Placestovisit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Placestovisit As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''KeyAttractions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KeyAttractions As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''GIR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GIR As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Somnath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Somnath As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''Booking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Booking As Global.System.Web.UI.WebControls.Localize
End Class
