'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DigitalGujaratPressRelease
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="DigitalGujaratPressRelease.DigitalGujaratSoap")>  _
    Public Interface DigitalGujaratSoap
        
        'CODEGEN: Generating message contract since element name PressReleasesForResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PressReleasesFor", ReplyAction:="*")>  _
        Function PressReleasesFor(ByVal request As DigitalGujaratPressRelease.PressReleasesForRequest) As DigitalGujaratPressRelease.PressReleasesForResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PressReleasesFor", ReplyAction:="*")>  _
        Function PressReleasesForAsync(ByVal request As DigitalGujaratPressRelease.PressReleasesForRequest) As System.Threading.Tasks.Task(Of DigitalGujaratPressRelease.PressReleasesForResponse)
        
        'CODEGEN: Generating message contract since element name LatestPressReleasesResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LatestPressReleases", ReplyAction:="*")>  _
        Function LatestPressReleases(ByVal request As DigitalGujaratPressRelease.LatestPressReleasesRequest) As DigitalGujaratPressRelease.LatestPressReleasesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LatestPressReleases", ReplyAction:="*")>  _
        Function LatestPressReleasesAsync(ByVal request As DigitalGujaratPressRelease.LatestPressReleasesRequest) As System.Threading.Tasks.Task(Of DigitalGujaratPressRelease.LatestPressReleasesResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PressReleasesForRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PressReleasesFor", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As DigitalGujaratPressRelease.PressReleasesForRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As DigitalGujaratPressRelease.PressReleasesForRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PressReleasesForRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public PR_Date As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PR_Date As Date)
            MyBase.New
            Me.PR_Date = PR_Date
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PressReleasesForResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PressReleasesForResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As DigitalGujaratPressRelease.PressReleasesForResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As DigitalGujaratPressRelease.PressReleasesForResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class PressReleasesForResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public PressReleasesForResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PressReleasesForResult As String)
            MyBase.New
            Me.PressReleasesForResult = PressReleasesForResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LatestPressReleasesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LatestPressReleases", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As DigitalGujaratPressRelease.LatestPressReleasesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As DigitalGujaratPressRelease.LatestPressReleasesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class LatestPressReleasesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LatestPressReleasesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LatestPressReleasesResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As DigitalGujaratPressRelease.LatestPressReleasesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As DigitalGujaratPressRelease.LatestPressReleasesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LatestPressReleasesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public LatestPressReleasesResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LatestPressReleasesResult As String)
            MyBase.New
            Me.LatestPressReleasesResult = LatestPressReleasesResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface DigitalGujaratSoapChannel
        Inherits DigitalGujaratPressRelease.DigitalGujaratSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DigitalGujaratSoapClient
        Inherits System.ServiceModel.ClientBase(Of DigitalGujaratPressRelease.DigitalGujaratSoap)
        Implements DigitalGujaratPressRelease.DigitalGujaratSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DigitalGujaratPressRelease_DigitalGujaratSoap_PressReleasesFor(ByVal request As DigitalGujaratPressRelease.PressReleasesForRequest) As DigitalGujaratPressRelease.PressReleasesForResponse Implements DigitalGujaratPressRelease.DigitalGujaratSoap.PressReleasesFor
            Return MyBase.Channel.PressReleasesFor(request)
        End Function
        
        Public Function PressReleasesFor(ByVal PR_Date As Date) As String
            Dim inValue As DigitalGujaratPressRelease.PressReleasesForRequest = New DigitalGujaratPressRelease.PressReleasesForRequest()
            inValue.Body = New DigitalGujaratPressRelease.PressReleasesForRequestBody()
            inValue.Body.PR_Date = PR_Date
            Dim retVal As DigitalGujaratPressRelease.PressReleasesForResponse = CType(Me,DigitalGujaratPressRelease.DigitalGujaratSoap).PressReleasesFor(inValue)
            Return retVal.Body.PressReleasesForResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DigitalGujaratPressRelease_DigitalGujaratSoap_PressReleasesForAsync(ByVal request As DigitalGujaratPressRelease.PressReleasesForRequest) As System.Threading.Tasks.Task(Of DigitalGujaratPressRelease.PressReleasesForResponse) Implements DigitalGujaratPressRelease.DigitalGujaratSoap.PressReleasesForAsync
            Return MyBase.Channel.PressReleasesForAsync(request)
        End Function
        
        Public Function PressReleasesForAsync(ByVal PR_Date As Date) As System.Threading.Tasks.Task(Of DigitalGujaratPressRelease.PressReleasesForResponse)
            Dim inValue As DigitalGujaratPressRelease.PressReleasesForRequest = New DigitalGujaratPressRelease.PressReleasesForRequest()
            inValue.Body = New DigitalGujaratPressRelease.PressReleasesForRequestBody()
            inValue.Body.PR_Date = PR_Date
            Return CType(Me,DigitalGujaratPressRelease.DigitalGujaratSoap).PressReleasesForAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DigitalGujaratPressRelease_DigitalGujaratSoap_LatestPressReleases(ByVal request As DigitalGujaratPressRelease.LatestPressReleasesRequest) As DigitalGujaratPressRelease.LatestPressReleasesResponse Implements DigitalGujaratPressRelease.DigitalGujaratSoap.LatestPressReleases
            Return MyBase.Channel.LatestPressReleases(request)
        End Function
        
        Public Function LatestPressReleases() As String
            Dim inValue As DigitalGujaratPressRelease.LatestPressReleasesRequest = New DigitalGujaratPressRelease.LatestPressReleasesRequest()
            inValue.Body = New DigitalGujaratPressRelease.LatestPressReleasesRequestBody()
            Dim retVal As DigitalGujaratPressRelease.LatestPressReleasesResponse = CType(Me,DigitalGujaratPressRelease.DigitalGujaratSoap).LatestPressReleases(inValue)
            Return retVal.Body.LatestPressReleasesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DigitalGujaratPressRelease_DigitalGujaratSoap_LatestPressReleasesAsync(ByVal request As DigitalGujaratPressRelease.LatestPressReleasesRequest) As System.Threading.Tasks.Task(Of DigitalGujaratPressRelease.LatestPressReleasesResponse) Implements DigitalGujaratPressRelease.DigitalGujaratSoap.LatestPressReleasesAsync
            Return MyBase.Channel.LatestPressReleasesAsync(request)
        End Function
        
        Public Function LatestPressReleasesAsync() As System.Threading.Tasks.Task(Of DigitalGujaratPressRelease.LatestPressReleasesResponse)
            Dim inValue As DigitalGujaratPressRelease.LatestPressReleasesRequest = New DigitalGujaratPressRelease.LatestPressReleasesRequest()
            inValue.Body = New DigitalGujaratPressRelease.LatestPressReleasesRequestBody()
            Return CType(Me,DigitalGujaratPressRelease.DigitalGujaratSoap).LatestPressReleasesAsync(inValue)
        End Function
    End Class
End Namespace
