'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace AppWS
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ATVT.guj.nic.in/", ConfigurationName:="AppWS.WebServiceSoap")>  _
    Public Interface WebServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ATVT.guj.nic.in/GetDataSet", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub GetDataSet(ByRef ds As System.Data.DataSet, ByVal index As Integer, ByVal enmWebServiceIndex As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ATVT.guj.nic.in/Insert", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub Insert(ByRef ds As System.Data.DataSet, ByVal index As Integer, ByVal enmWebServiceIndex As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ATVT.guj.nic.in/InsertReturn", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertReturn(ByRef ds As System.Data.DataSet, ByVal index As Integer, ByVal enmWebServiceIndex As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ATVT.guj.nic.in/Update", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub Update(ByRef ds As System.Data.DataSet, ByVal index As Integer, ByVal enmWebServiceIndex As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ATVT.guj.nic.in/FindDataSet", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub FindDataSet(ByRef ds As System.Data.DataSet, ByVal index As Integer, ByVal enmWebServiceIndex As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ATVT.guj.nic.in/Delete", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub Delete(ByRef ds As System.Data.DataSet, ByVal strCriteria As String, ByVal index As Integer, ByVal enmWebServiceIndex As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ATVT.guj.nic.in/SendSMS", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SendSMS(ByVal key As String, ByVal mobileno As String, ByVal strsms As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ATVT.guj.nic.in/GetUserID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetUserID(ByVal username As String, ByVal password As String, ByVal Salt As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebServiceSoapChannel
        Inherits AppWS.WebServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of AppWS.WebServiceSoap)
        Implements AppWS.WebServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub GetDataSet(ByRef ds As System.Data.DataSet, ByVal index As Integer, ByVal enmWebServiceIndex As Integer) Implements AppWS.WebServiceSoap.GetDataSet
            MyBase.Channel.GetDataSet(ds, index, enmWebServiceIndex)
        End Sub
        
        Public Sub Insert(ByRef ds As System.Data.DataSet, ByVal index As Integer, ByVal enmWebServiceIndex As Integer) Implements AppWS.WebServiceSoap.Insert
            MyBase.Channel.Insert(ds, index, enmWebServiceIndex)
        End Sub
        
        Public Function InsertReturn(ByRef ds As System.Data.DataSet, ByVal index As Integer, ByVal enmWebServiceIndex As Integer) As String Implements AppWS.WebServiceSoap.InsertReturn
            Return MyBase.Channel.InsertReturn(ds, index, enmWebServiceIndex)
        End Function
        
        Public Sub Update(ByRef ds As System.Data.DataSet, ByVal index As Integer, ByVal enmWebServiceIndex As Integer) Implements AppWS.WebServiceSoap.Update
            MyBase.Channel.Update(ds, index, enmWebServiceIndex)
        End Sub
        
        Public Sub FindDataSet(ByRef ds As System.Data.DataSet, ByVal index As Integer, ByVal enmWebServiceIndex As Integer) Implements AppWS.WebServiceSoap.FindDataSet
            MyBase.Channel.FindDataSet(ds, index, enmWebServiceIndex)
        End Sub
        
        Public Sub Delete(ByRef ds As System.Data.DataSet, ByVal strCriteria As String, ByVal index As Integer, ByVal enmWebServiceIndex As Integer) Implements AppWS.WebServiceSoap.Delete
            MyBase.Channel.Delete(ds, strCriteria, index, enmWebServiceIndex)
        End Sub
        
        Public Function SendSMS(ByVal key As String, ByVal mobileno As String, ByVal strsms As String) As String Implements AppWS.WebServiceSoap.SendSMS
            Return MyBase.Channel.SendSMS(key, mobileno, strsms)
        End Function
        
        Public Function GetUserID(ByVal username As String, ByVal password As String, ByVal Salt As String) As String Implements AppWS.WebServiceSoap.GetUserID
            Return MyBase.Channel.GetUserID(username, password, Salt)
        End Function
    End Class
End Namespace
