'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MoreApps

    '''<summary>
    '''localize1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize1 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize2 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize3 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize4 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize5 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize6 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize7 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize8 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize9 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize10 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize11 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize12 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize13 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize14 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize15 As Global.System.Web.UI.WebControls.Localize

    '''<summary>
    '''localize16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents localize16 As Global.System.Web.UI.WebControls.Localize
End Class
