'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace AdminService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AdminService.AdminServiceSoap")>  _
    Public Interface AdminServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUserLog", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUserLog(ByVal UId As Integer, ByVal FDate As Date, ByVal TDate As Date) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getMData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getMData(ByVal Fld As String, ByVal Tbl As String, ByVal Cnd As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getAnganwadi", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getAnganwadi(ByVal Typ As String, ByVal Cd As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUserBy_DT_ODID_DID_AID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUserBy_DT_ODID_DID_AID(ByVal DCODE As Integer, ByVal TCODE As String, ByVal ODID As Short, ByVal DesiID As Short, ByVal AppID As Short) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUserByOfficeID_DesiID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUserByOfficeID_DesiID(ByVal OfficeID As Integer, ByVal DesiID As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUserBy_OfficeID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUserBy_OfficeID(ByVal OfficeID As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUserRawData", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUserRawData(ByVal UserID As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getFPS_Data", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getFPS_Data(ByVal OfficeID As Integer, ByVal AppID As Integer, ByVal UserID As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getDesignation", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getDesignation(ByVal OfficeID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getOfficeDefinition", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getOfficeDefinition(ByVal DeptId As Short) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getOffice_ByParent", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getOffice_ByParent(ByVal ParentID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getOffice", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getOffice(ByVal OfficeID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUserID_with_DisposeToken", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUserID_with_DisposeToken(ByVal GId As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getLogoutToken", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getLogoutToken(ByVal uid As Integer, ByVal URL As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUsersByApplication", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUsersByApplication(ByVal AppId As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getOfficeByODID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getOfficeByODID(ByVal ODID As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getOfficeByDistrict_State", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getOfficeByDistrict_State(ByVal DCode As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUserByApplication", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUserByApplication(ByVal UserID As Integer, ByVal AppId As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getDepartments", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getDepartments(ByVal deptid As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getOfficesByDept", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getOfficesByDept(ByVal DeptID As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getOfficesByApplication", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getOfficesByApplication(ByVal AppId As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUserWorkarea", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUserWorkarea(ByVal UserID As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUser", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUser(ByVal UserID As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUserOfApp", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUserOfApp(ByVal UserID As Integer, ByVal AppID As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/isApplication_Manager", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function isApplication_Manager(ByVal UserID As Integer, ByVal ApplicationID As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUserAppRole", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUserAppRole(ByVal UserID As Integer, ByVal ApplicationID As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VerifyFinger", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function VerifyFinger(ByVal UserID As Integer, ByVal FingerName As String, ByVal FingerData As String) As String
        
        'CODEGEN: Parameter 'getUserSignResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUserSign", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUserSign(ByVal request As AdminService.getUserSignRequest) As AdminService.getUserSignResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUserDefaultFP", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUserDefaultFP(ByVal UserID As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/isValidUser", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function isValidUser(ByVal UserName As String, ByVal PWD As String, ByVal Salt As String, ByVal AppStartPageURL As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUser_By_EncryptedGID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUser_By_EncryptedGID(ByVal GId As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUser_in_XML", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUser_in_XML(ByVal UserID As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUsersByDept", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getUsersByDept(ByVal DeptId As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ROR_USERLIST", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ROR_USERLIST(ByVal DCODE As Integer, ByVal TCODE As Integer, ByVal LEVEL As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UserLogout", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UserLogout(ByVal AUID As Integer, ByVal UID As Integer, ByVal WebPage As String, ByVal Action As String, ByVal Detail As String, ByVal ClientIP As String, ByVal Dt As Date) As Object
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/get_Menu_Details", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_Menu_Details(ByVal User_Name As String) As System.Data.DataSet
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getUserSign", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getUserSignRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public UserID As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserID As Integer)
            MyBase.New
            Me.UserID = UserID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getUserSignResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getUserSignResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public getUserSignResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getUserSignResult() As Byte)
            MyBase.New
            Me.getUserSignResult = getUserSignResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface AdminServiceSoapChannel
        Inherits AdminService.AdminServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AdminServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of AdminService.AdminServiceSoap)
        Implements AdminService.AdminServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function getUserLog(ByVal UId As Integer, ByVal FDate As Date, ByVal TDate As Date) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getUserLog
            Return MyBase.Channel.getUserLog(UId, FDate, TDate)
        End Function
        
        Public Function getMData(ByVal Fld As String, ByVal Tbl As String, ByVal Cnd As String) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getMData
            Return MyBase.Channel.getMData(Fld, Tbl, Cnd)
        End Function
        
        Public Function getAnganwadi(ByVal Typ As String, ByVal Cd As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getAnganwadi
            Return MyBase.Channel.getAnganwadi(Typ, Cd)
        End Function
        
        Public Function getUserBy_DT_ODID_DID_AID(ByVal DCODE As Integer, ByVal TCODE As String, ByVal ODID As Short, ByVal DesiID As Short, ByVal AppID As Short) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getUserBy_DT_ODID_DID_AID
            Return MyBase.Channel.getUserBy_DT_ODID_DID_AID(DCODE, TCODE, ODID, DesiID, AppID)
        End Function
        
        Public Function getUserByOfficeID_DesiID(ByVal OfficeID As Integer, ByVal DesiID As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getUserByOfficeID_DesiID
            Return MyBase.Channel.getUserByOfficeID_DesiID(OfficeID, DesiID)
        End Function
        
        Public Function getUserBy_OfficeID(ByVal OfficeID As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getUserBy_OfficeID
            Return MyBase.Channel.getUserBy_OfficeID(OfficeID)
        End Function
        
        Public Function getUserRawData(ByVal UserID As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getUserRawData
            Return MyBase.Channel.getUserRawData(UserID)
        End Function
        
        Public Function getFPS_Data(ByVal OfficeID As Integer, ByVal AppID As Integer, ByVal UserID As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getFPS_Data
            Return MyBase.Channel.getFPS_Data(OfficeID, AppID, UserID)
        End Function
        
        Public Function getDesignation(ByVal OfficeID As String) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getDesignation
            Return MyBase.Channel.getDesignation(OfficeID)
        End Function
        
        Public Function getOfficeDefinition(ByVal DeptId As Short) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getOfficeDefinition
            Return MyBase.Channel.getOfficeDefinition(DeptId)
        End Function
        
        Public Function getOffice_ByParent(ByVal ParentID As String) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getOffice_ByParent
            Return MyBase.Channel.getOffice_ByParent(ParentID)
        End Function
        
        Public Function getOffice(ByVal OfficeID As String) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getOffice
            Return MyBase.Channel.getOffice(OfficeID)
        End Function
        
        Public Function getUserID_with_DisposeToken(ByVal GId As String) As Integer Implements AdminService.AdminServiceSoap.getUserID_with_DisposeToken
            Return MyBase.Channel.getUserID_with_DisposeToken(GId)
        End Function
        
        Public Function getLogoutToken(ByVal uid As Integer, ByVal URL As String) As String Implements AdminService.AdminServiceSoap.getLogoutToken
            Return MyBase.Channel.getLogoutToken(uid, URL)
        End Function
        
        Public Function getUsersByApplication(ByVal AppId As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getUsersByApplication
            Return MyBase.Channel.getUsersByApplication(AppId)
        End Function
        
        Public Function getOfficeByODID(ByVal ODID As String) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getOfficeByODID
            Return MyBase.Channel.getOfficeByODID(ODID)
        End Function
        
        Public Function getOfficeByDistrict_State(ByVal DCode As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getOfficeByDistrict_State
            Return MyBase.Channel.getOfficeByDistrict_State(DCode)
        End Function
        
        Public Function getUserByApplication(ByVal UserID As Integer, ByVal AppId As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getUserByApplication
            Return MyBase.Channel.getUserByApplication(UserID, AppId)
        End Function
        
        Public Function getDepartments(ByVal deptid As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getDepartments
            Return MyBase.Channel.getDepartments(deptid)
        End Function
        
        Public Function getOfficesByDept(ByVal DeptID As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getOfficesByDept
            Return MyBase.Channel.getOfficesByDept(DeptID)
        End Function
        
        Public Function getOfficesByApplication(ByVal AppId As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getOfficesByApplication
            Return MyBase.Channel.getOfficesByApplication(AppId)
        End Function
        
        Public Function getUserWorkarea(ByVal UserID As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getUserWorkarea
            Return MyBase.Channel.getUserWorkarea(UserID)
        End Function
        
        Public Function getUser(ByVal UserID As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getUser
            Return MyBase.Channel.getUser(UserID)
        End Function
        
        Public Function getUserOfApp(ByVal UserID As Integer, ByVal AppID As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getUserOfApp
            Return MyBase.Channel.getUserOfApp(UserID, AppID)
        End Function
        
        Public Function isApplication_Manager(ByVal UserID As Integer, ByVal ApplicationID As Integer) As Boolean Implements AdminService.AdminServiceSoap.isApplication_Manager
            Return MyBase.Channel.isApplication_Manager(UserID, ApplicationID)
        End Function
        
        Public Function getUserAppRole(ByVal UserID As Integer, ByVal ApplicationID As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getUserAppRole
            Return MyBase.Channel.getUserAppRole(UserID, ApplicationID)
        End Function
        
        Public Function VerifyFinger(ByVal UserID As Integer, ByVal FingerName As String, ByVal FingerData As String) As String Implements AdminService.AdminServiceSoap.VerifyFinger
            Return MyBase.Channel.VerifyFinger(UserID, FingerName, FingerData)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AdminService_AdminServiceSoap_getUserSign(ByVal request As AdminService.getUserSignRequest) As AdminService.getUserSignResponse Implements AdminService.AdminServiceSoap.getUserSign
            Return MyBase.Channel.getUserSign(request)
        End Function
        
        Public Function getUserSign(ByVal UserID As Integer) As Byte()
            Dim inValue As AdminService.getUserSignRequest = New AdminService.getUserSignRequest()
            inValue.UserID = UserID
            Dim retVal As AdminService.getUserSignResponse = CType(Me,AdminService.AdminServiceSoap).getUserSign(inValue)
            Return retVal.getUserSignResult
        End Function
        
        Public Function getUserDefaultFP(ByVal UserID As Integer) As String Implements AdminService.AdminServiceSoap.getUserDefaultFP
            Return MyBase.Channel.getUserDefaultFP(UserID)
        End Function
        
        Public Function isValidUser(ByVal UserName As String, ByVal PWD As String, ByVal Salt As String, ByVal AppStartPageURL As String) As String Implements AdminService.AdminServiceSoap.isValidUser
            Return MyBase.Channel.isValidUser(UserName, PWD, Salt, AppStartPageURL)
        End Function
        
        Public Function getUser_By_EncryptedGID(ByVal GId As String) As Integer Implements AdminService.AdminServiceSoap.getUser_By_EncryptedGID
            Return MyBase.Channel.getUser_By_EncryptedGID(GId)
        End Function
        
        Public Function getUser_in_XML(ByVal UserID As Integer) As String Implements AdminService.AdminServiceSoap.getUser_in_XML
            Return MyBase.Channel.getUser_in_XML(UserID)
        End Function
        
        Public Function getUsersByDept(ByVal DeptId As Integer) As System.Data.DataSet Implements AdminService.AdminServiceSoap.getUsersByDept
            Return MyBase.Channel.getUsersByDept(DeptId)
        End Function
        
        Public Function ROR_USERLIST(ByVal DCODE As Integer, ByVal TCODE As Integer, ByVal LEVEL As String) As System.Data.DataSet Implements AdminService.AdminServiceSoap.ROR_USERLIST
            Return MyBase.Channel.ROR_USERLIST(DCODE, TCODE, LEVEL)
        End Function
        
        Public Function UserLogout(ByVal AUID As Integer, ByVal UID As Integer, ByVal WebPage As String, ByVal Action As String, ByVal Detail As String, ByVal ClientIP As String, ByVal Dt As Date) As Object Implements AdminService.AdminServiceSoap.UserLogout
            Return MyBase.Channel.UserLogout(AUID, UID, WebPage, Action, Detail, ClientIP, Dt)
        End Function
        
        Public Function get_Menu_Details(ByVal User_Name As String) As System.Data.DataSet Implements AdminService.AdminServiceSoap.get_Menu_Details
            Return MyBase.Channel.get_Menu_Details(User_Name)
        End Function
    End Class
End Namespace
